# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Toneclone < Formula
  desc "AI-powered writing assistance from the command line"
  homepage "https://github.com/toneclone/cli"
  version "1.0.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/toneclone/cli/releases/download/v1.0.3/toneclone_1.0.3_Darwin_x86_64.tar.gz"
      sha256 "d66436fc74a5d5f4af57f6393d4bfca82cc84f4b18705b9f9eb83a8687bd6425"

      def install
        bin.install "toneclone"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/toneclone/cli/releases/download/v1.0.3/toneclone_1.0.3_Darwin_arm64.tar.gz"
      sha256 "622e77bcb8053177205bcc663e485f0e57f5814da149122300a6cb0c68a69a57"

      def install
        bin.install "toneclone"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/toneclone/cli/releases/download/v1.0.3/toneclone_1.0.3_Linux_x86_64.tar.gz"
      sha256 "9e56e13ddb44aee66d1cdfc24bbb41d14e30951c6a7b260a94275c61fbc7e2a8"
      def install
        bin.install "toneclone"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/toneclone/cli/releases/download/v1.0.3/toneclone_1.0.3_Linux_arm64.tar.gz"
      sha256 "6a289fe3eb2b6be093ed4981cb7be3ed399d80e27aa6da0294e56dea3fe44af6"
      def install
        bin.install "toneclone"
      end
    end
  end

  test do
    system "#{bin}/toneclone --version"
  end
end
