# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Toneclone < Formula
  desc "AI-powered writing assistance from the command line"
  homepage "https://github.com/toneclone/cli"
  version "1.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/toneclone/cli/releases/download/v1.1.1/toneclone_darwin_amd64.tar.gz"
      sha256 "f9071ab7c1021c23589c86cbfdf1114da195ce2dd9b2659a9ec81b8b05e16704"

      def install
        bin.install "toneclone"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/toneclone/cli/releases/download/v1.1.1/toneclone_darwin_arm64.tar.gz"
      sha256 "32940965154f48ff170f76cfb76fb6e5f805a7f766ff7d49ac43807c66665f1b"

      def install
        bin.install "toneclone"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/toneclone/cli/releases/download/v1.1.1/toneclone_linux_amd64.tar.gz"
      sha256 "280ab0ccd699eb64b52ed3e4ed0dc04f2caedbbb44104746adeacc906ed0d4ab"
      def install
        bin.install "toneclone"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/toneclone/cli/releases/download/v1.1.1/toneclone_linux_arm64.tar.gz"
      sha256 "44f85ea600389e2293037f6ddc88cb178f0ce25c3de80315b1b3a4eddb6fff8e"
      def install
        bin.install "toneclone"
      end
    end
  end

  test do
    system "#{bin}/toneclone --version"
  end
end
